In [1]:
import numpy as np
import os
import sys
import cv2
import urllib2
import urllib

In [2]:
home_dir = os.getenv("HOME")
caffe_root = os.path.join(home_dir, 'caffe')
sys.path.insert(0, os.path.join(caffe_root, 'python'))

import caffe

In [3]:
class NetFace:
    
    def __init__(self):
        path = "haarcascade_frontalface_alt.xml"
        self.classifier = cv2.CascadeClassifier(path)
    def classifierImage(self,miniframe):
        return self.classifier.detectMultiScale(miniframe)

In [4]:
class Face:
    
    def __init__(self,net=NetFace()):
        self.net = net

    def detect(self,frame):
        height, width, depth = frame.shape

        # create grayscale version
        grayscale = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        # equalize histogram
        cv2.equalizeHist(grayscale, grayscale)

        # detect objects
        DOWNSCALE = 4
        minisize = (frame.shape[1]/DOWNSCALE,frame.shape[0]/DOWNSCALE)
        miniframe = cv2.resize(frame, minisize)
        faces = self.net.classifierImage(miniframe)
        
        # show rectangles on the faces
        #if len(faces)>0:
        #    for i in faces:
        #        x, y, w, h = [ v*DOWNSCALE for v in i ]
        #        cv2.rectangle(frame, (x,y), (x+w,y+h), (0,255,0))
        #        cv2.imshow('frame',frame)
        #        
        #        cv2.waitKey(0)
        #        
        #        print("Faces: ", len(faces))
        
        return faces

In [5]:
class NetData:

    def __init__(self,net,transformer,labels):
        self.transformer = transformer
        self.labels = labels
        self.net = net

    def get_transformer(self):
        return self.transformer

    def get_labels(self):
        return self.labels

    def get_net(self):
        return self.net

In [6]:
class Net:

    def __init__(self,net,transformer,labels):
        self.netData = NetData(net,transformer,labels)
        self.loadsynset()
        
    def loadsynset(self):
        f = open("synset_cats","r")
        self.cats = f.read().splitlines()
        f.close()
        
        f = open("synset_dogs","r")
        self.dogs = f.read().splitlines()
        f.close()

    def predict_imageNet(self,image_filename):
        image = caffe.io.load_image(image_filename)
        self.netData.get_net().blobs['data'].data[...] = self.netData.get_transformer().preprocess('data', image)

        # perform classification
        self.netData.get_net().forward()

        # obtain the output probabilities
        output_prob = self.netData.get_net().blobs['prob'].data[0]

        # sort top five predictions from softmax output
        top_inds = output_prob.argsort()[::-1][:5]

        predictions = zip(output_prob[top_inds], self.netData.get_labels()[top_inds])

        return predictions

    def result(self,img):
        predictions = self.predict_imageNet(img)
        total_dogs = 0
        total_cats = 0
        
        for per, cls in predictions:
            if cls.split()[0] in self.cats:
                total_cats += per

            elif cls.split()[0] in self.dogs:
                total_dogs += per
        
        return total_dogs*100,total_cats*100

In [7]:
class Input:

    FACES = 1
    PREDICTION = 2

    def __init__(self, load=None):
        self.img = None
        if(load): self.resolve(load)

    def resolve(self,load):
        if(self.isFile(load)):
            self.fileResolver(load)	
        
        elif(self.isUrl(load)):
            self.urlResolver(load)

    def isFile(self,load):
        return os.path.isfile(load)

    def isUrl(self,load):
        try:
            urllib2.urlopen(load)
            return True

        except urllib2.HTTPError, e:
            return False
        
        except urllib2.URLError, e:
            return False

        return False

    def fileResolver(self,load):
        self.img = cv2.imread(load)
        self.load = load

    def urlResolver(self,load):
        image = urllib.URLopener()
        path = "Images"
        image.retrieve(load,path)
        image.close()
        self.fileResolver(path)
        
        return None

    def getImage(self,destination):
        if(destination == self.FACES):
            return self.img

        else:
            return self.load

In [8]:
class Output:

    def outFaces(self,faces):
        if(len(faces) > 0):
            print("Foram detectadas {0} faces.").format(str(len(faces)))
            print("As coordenadas das faces são: ")

            for face in faces:
                print(face)
        
        else:
            print("Não foram encontradas faces.")

        
    def outAnimals(self,dogs,cats):
        if(dogs > 0):
            print("A probabilidade de haver cães na imagem é de: {0}%.").format(str(dogs))

        else:
            print("Não há cães na imagem.")

        if(cats > 0):
            print("A probabilidade de haver gatos na imagem é de: {0}%.").format(str(cats))

        else:
            print("Não há gatos na imagem.")

In [9]:
def main(argv=sys.argv):
    mu = np.load(os.path.join(caffe_root, 'python','caffe','imagenet','ilsvrc_2012_mean.npy'))
    mu = mu.mean(1).mean(1)  

    model_weights = os.path.join(caffe_root, 'models','bvlc_reference_caffenet','bvlc_reference_caffenet.caffemodel')
    model_def = os.path.join(caffe_root, 'models', 'bvlc_reference_caffenet','deploy.prototxt')
    net = caffe.Net(model_def,model_weights,caffe.TEST)

    transformer = caffe.io.Transformer({'data': net.blobs['data'].data.shape})
    transformer.set_transpose('data', (2,0,1))
    transformer.set_mean('data', mu)      
    transformer.set_raw_scale('data', 255)      
    transformer.set_channel_swap('data', (2,1,0)) 

    labels_file = os.path.join(caffe_root, 'data','ilsvrc12','synset_words.txt')
    labels = np.loadtxt(labels_file, str, delimiter='\t') 

    f = Face()
    n = Net(net,transformer,labels)
    o = Output()
    
    if(len(argv) >= 2):
        argv.pop(0)
    
        for arg in argv:
            print(arg)
            d = Input(arg)
            o.outFaces(f.detect(d.getImage(Input.FACES)))
            dogs,cats = n.result(d.getImage(Input.PREDICTION))
            o.outAnimals(dogs,cats)

In [10]:
img_dir = 'Images'
images = os.listdir(img_dir)

In [11]:
for img_file in images:
    main([" ", os.path.join(img_dir, img_file)])
    print "\n"

Images/Cachorro-1.jpg
Não foram encontradas faces.
A probabilidade de haver cães na imagem é de: 44.1126599908%.
Não há gatos na imagem.


Images/Gato-1.jpg
Não foram encontradas faces.
Não há cães na imagem.
A probabilidade de haver gatos na imagem é de: 67.4296088517%.


Images/Familia-com-Cachorro.jpg
Foram detectadas 3 faces.
As coordenadas das faces são: 
[129  22  31  31]
[85 94 45 45]
[138  97  64  64]
A probabilidade de haver cães na imagem é de: 39.8055158556%.
Não há gatos na imagem.


Images/Gato-2.jpg
Não foram encontradas faces.
Não há cães na imagem.
A probabilidade de haver gatos na imagem é de: 99.996507098%.


Images/Pessoa.jpg
Foram detectadas 1 faces.
As coordenadas das faces são: 
[ 34  37 118 118]
Não há cães na imagem.
Não há gatos na imagem.


Images/Familia.jpg
Foram detectadas 2 faces.
As coordenadas das faces são: 
[76 12 28 28]
[104   8  36  36]
Não há cães na imagem.
Não há gatos na imagem.


Images/Cachorro-2.jpg
Foram detectadas 1 faces.
As coordenadas das

In [11]:
import unittest

class TestFace(unittest.TestCase):
    f = Face()
    o = Output()
    img_dir = 'Images'
    
    def test_more_than_1_face (self):
        image = os.path.join(img_dir, 'Familia.jpg')
        faces = f.detect(d.getImage(Input.FACES))
        
        d = Input(image)
        o.outFaces(faces)
        self.assertEqual(str(len(faces)),2)

    if __name__ == "__main__":
        suite = unittest.TestSuite()
    
        for method in dir(TestFace):
            if method.startswith("test"):
                suite.addTest(TestFace(method))
        unittest.TextTestRunner().run(suite)

NameError: name 'TestFace' is not defined